name: publish
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@meiti-x'
      - run: npm i
      - run: npm run build
      - run: |
          echo @meiti-x:https://npm.pkg.github.com/meiti-x/ > build/.npmrc
          echo //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN} >> build/.npmrc
      - run: npm publish
        working-directory: ./build
        env: 
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}